#!/bin/sh
export PYTHONPATH=/home/beomjoon/Documents/Github/drake-distro/build/lib/python2.7/dist-packages:/home/beomjoon/Documents/Github/drake-distro/build/lib/python2.7/site-packages:${PYTHONPATH}
exec /usr/bin/python -m bot_procman.sheriff_gtk.sheriff_gtk $*
