# CMake generated Testfile for 
# Source directory: /home/beomjoon/Documents/Github/drake-distro/snopt/examples
# Build directory: /home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(sntoya "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/sntoya")
ADD_TEST(sntoyb "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/sntoyb")
ADD_TEST(sntoyc "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/sntoyc")
ADD_TEST(snchka "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/snchka")
ADD_TEST(snmaina "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/snmaina")
ADD_TEST(snmainb "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/snmainb")
ADD_TEST(snmainc "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/snmainc")
ADD_TEST(slmain "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/slmain")
ADD_TEST(npmain "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/npmain")
ADD_TEST(hsmaina "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/hsmaina")
ADD_TEST(hsmainc "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/hsmainc")
ADD_TEST(sqmain "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/sqmain")
ADD_TEST(sqmain2 "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/sqmain2")
ADD_TEST(snmemtesta "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/snmemtesta")
ADD_TEST(snmemtestb "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/snmemtestb")
ADD_TEST(catmixa "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/catmixa")
ADD_TEST(catmixb "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/catmixb")
ADD_TEST(catmixc "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/catmixc")
ADD_TEST(testera "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/testera")
ADD_TEST(tester "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/tester")
ADD_TEST(t1dieta "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/t1dieta")
ADD_TEST(t1dietb "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/t1dietb")
ADD_TEST(t2bananaa "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/t2bananaa")
ADD_TEST(t2bananab "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/t2bananab")
ADD_TEST(t3qp "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/t3qp")
ADD_TEST(t4mannea "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/t4mannea")
ADD_TEST(t4manneb "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/t4manneb")
ADD_TEST(t4mannec "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/t4mannec")
ADD_TEST(t5weapon "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/t5weapon")
ADD_TEST(t6wood "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/t6wood")
ADD_TEST(t7etamacro "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/t7etamacro")
ADD_TEST(calvara "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/calvara")
ADD_TEST(springa "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/springa")
ADD_TEST(springb "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/springb")
ADD_TEST(springib "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/springib")
ADD_TEST(maxi "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/maxi")
ADD_TEST(hs118 "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/hs118")
ADD_TEST(slmainMPS "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/slmainMPS")
ADD_TEST(sqmainMPS "/home/beomjoon/Documents/Github/drake-distro/snopt/pod-build/bin/sqmainMPS")
