/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "drake_lcmt_robot_state.h"

static int __drake_lcmt_robot_state_hash_computed;
static int64_t __drake_lcmt_robot_state_hash;

int64_t __drake_lcmt_robot_state_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __drake_lcmt_robot_state_get_hash)
            return 0;

    const __lcm_hash_ptr cp = { p, (void*)__drake_lcmt_robot_state_get_hash };
    (void) cp;

    int64_t hash = 0x5ee54c65cb66563dLL
         + __int64_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __string_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __string_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __drake_lcmt_robot_state_get_hash(void)
{
    if (!__drake_lcmt_robot_state_hash_computed) {
        __drake_lcmt_robot_state_hash = __drake_lcmt_robot_state_hash_recursive(NULL);
        __drake_lcmt_robot_state_hash_computed = 1;
    }

    return __drake_lcmt_robot_state_hash;
}

int __drake_lcmt_robot_state_encode_array(void *buf, int offset, int maxlen, const drake_lcmt_robot_state *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].num_robots), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_encode_array(buf, offset + pos, maxlen - pos, p[element].robot_name, p[element].num_robots);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].num_joints), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, p[element].joint_robot, p[element].num_joints);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_encode_array(buf, offset + pos, maxlen - pos, p[element].joint_name, p[element].num_joints);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].joint_position, p[element].num_joints);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, p[element].joint_velocity, p[element].num_joints);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int drake_lcmt_robot_state_encode(void *buf, int offset, int maxlen, const drake_lcmt_robot_state *p)
{
    int pos = 0, thislen;
    int64_t hash = __drake_lcmt_robot_state_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __drake_lcmt_robot_state_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __drake_lcmt_robot_state_encoded_array_size(const drake_lcmt_robot_state *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].timestamp), 1);

        size += __int32_t_encoded_array_size(&(p[element].num_robots), 1);

        size += __string_encoded_array_size(p[element].robot_name, p[element].num_robots);

        size += __int32_t_encoded_array_size(&(p[element].num_joints), 1);

        size += __int32_t_encoded_array_size(p[element].joint_robot, p[element].num_joints);

        size += __string_encoded_array_size(p[element].joint_name, p[element].num_joints);

        size += __float_encoded_array_size(p[element].joint_position, p[element].num_joints);

        size += __float_encoded_array_size(p[element].joint_velocity, p[element].num_joints);

    }
    return size;
}

int drake_lcmt_robot_state_encoded_size(const drake_lcmt_robot_state *p)
{
    return 8 + __drake_lcmt_robot_state_encoded_array_size(p, 1);
}

int __drake_lcmt_robot_state_decode_array(const void *buf, int offset, int maxlen, drake_lcmt_robot_state *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].num_robots), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].robot_name = (char**) lcm_malloc(sizeof(char*) * p[element].num_robots);
        thislen = __string_decode_array(buf, offset + pos, maxlen - pos, p[element].robot_name, p[element].num_robots);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].num_joints), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].joint_robot = (int32_t*) lcm_malloc(sizeof(int32_t) * p[element].num_joints);
        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, p[element].joint_robot, p[element].num_joints);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].joint_name = (char**) lcm_malloc(sizeof(char*) * p[element].num_joints);
        thislen = __string_decode_array(buf, offset + pos, maxlen - pos, p[element].joint_name, p[element].num_joints);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].joint_position = (float*) lcm_malloc(sizeof(float) * p[element].num_joints);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].joint_position, p[element].num_joints);
        if (thislen < 0) return thislen; else pos += thislen;

        p[element].joint_velocity = (float*) lcm_malloc(sizeof(float) * p[element].num_joints);
        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, p[element].joint_velocity, p[element].num_joints);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __drake_lcmt_robot_state_decode_array_cleanup(drake_lcmt_robot_state *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].timestamp), 1);

        __int32_t_decode_array_cleanup(&(p[element].num_robots), 1);

        __string_decode_array_cleanup(p[element].robot_name, p[element].num_robots);
        if (p[element].robot_name) free(p[element].robot_name);

        __int32_t_decode_array_cleanup(&(p[element].num_joints), 1);

        __int32_t_decode_array_cleanup(p[element].joint_robot, p[element].num_joints);
        if (p[element].joint_robot) free(p[element].joint_robot);

        __string_decode_array_cleanup(p[element].joint_name, p[element].num_joints);
        if (p[element].joint_name) free(p[element].joint_name);

        __float_decode_array_cleanup(p[element].joint_position, p[element].num_joints);
        if (p[element].joint_position) free(p[element].joint_position);

        __float_decode_array_cleanup(p[element].joint_velocity, p[element].num_joints);
        if (p[element].joint_velocity) free(p[element].joint_velocity);

    }
    return 0;
}

int drake_lcmt_robot_state_decode(const void *buf, int offset, int maxlen, drake_lcmt_robot_state *p)
{
    int pos = 0, thislen;
    int64_t hash = __drake_lcmt_robot_state_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __drake_lcmt_robot_state_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int drake_lcmt_robot_state_decode_cleanup(drake_lcmt_robot_state *p)
{
    return __drake_lcmt_robot_state_decode_array_cleanup(p, 1);
}

int __drake_lcmt_robot_state_clone_array(const drake_lcmt_robot_state *p, drake_lcmt_robot_state *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].timestamp), &(q[element].timestamp), 1);

        __int32_t_clone_array(&(p[element].num_robots), &(q[element].num_robots), 1);

        q[element].robot_name = (char**) lcm_malloc(sizeof(char*) * q[element].num_robots);
        __string_clone_array(p[element].robot_name, q[element].robot_name, p[element].num_robots);

        __int32_t_clone_array(&(p[element].num_joints), &(q[element].num_joints), 1);

        q[element].joint_robot = (int32_t*) lcm_malloc(sizeof(int32_t) * q[element].num_joints);
        __int32_t_clone_array(p[element].joint_robot, q[element].joint_robot, p[element].num_joints);

        q[element].joint_name = (char**) lcm_malloc(sizeof(char*) * q[element].num_joints);
        __string_clone_array(p[element].joint_name, q[element].joint_name, p[element].num_joints);

        q[element].joint_position = (float*) lcm_malloc(sizeof(float) * q[element].num_joints);
        __float_clone_array(p[element].joint_position, q[element].joint_position, p[element].num_joints);

        q[element].joint_velocity = (float*) lcm_malloc(sizeof(float) * q[element].num_joints);
        __float_clone_array(p[element].joint_velocity, q[element].joint_velocity, p[element].num_joints);

    }
    return 0;
}

drake_lcmt_robot_state *drake_lcmt_robot_state_copy(const drake_lcmt_robot_state *p)
{
    drake_lcmt_robot_state *q = (drake_lcmt_robot_state*) malloc(sizeof(drake_lcmt_robot_state));
    __drake_lcmt_robot_state_clone_array(p, q, 1);
    return q;
}

void drake_lcmt_robot_state_destroy(drake_lcmt_robot_state *p)
{
    __drake_lcmt_robot_state_decode_array_cleanup(p, 1);
    free(p);
}

int drake_lcmt_robot_state_publish(lcm_t *lc, const char *channel, const drake_lcmt_robot_state *p)
{
      int max_data_size = drake_lcmt_robot_state_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = drake_lcmt_robot_state_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _drake_lcmt_robot_state_subscription_t {
    drake_lcmt_robot_state_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void drake_lcmt_robot_state_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    drake_lcmt_robot_state p;
    memset(&p, 0, sizeof(drake_lcmt_robot_state));
    status = drake_lcmt_robot_state_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding drake_lcmt_robot_state!!!\n", status);
        return;
    }

    drake_lcmt_robot_state_subscription_t *h = (drake_lcmt_robot_state_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    drake_lcmt_robot_state_decode_cleanup (&p);
}

drake_lcmt_robot_state_subscription_t* drake_lcmt_robot_state_subscribe (lcm_t *lcm,
                    const char *channel,
                    drake_lcmt_robot_state_handler_t f, void *userdata)
{
    drake_lcmt_robot_state_subscription_t *n = (drake_lcmt_robot_state_subscription_t*)
                       malloc(sizeof(drake_lcmt_robot_state_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 drake_lcmt_robot_state_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg drake_lcmt_robot_state LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int drake_lcmt_robot_state_subscription_set_queue_capacity (drake_lcmt_robot_state_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int drake_lcmt_robot_state_unsubscribe(lcm_t *lcm, drake_lcmt_robot_state_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe drake_lcmt_robot_state_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

