/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "drake_lcmt_scope_data.h"

static int __drake_lcmt_scope_data_hash_computed;
static int64_t __drake_lcmt_scope_data_hash;

int64_t __drake_lcmt_scope_data_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __drake_lcmt_scope_data_get_hash)
            return 0;

    const __lcm_hash_ptr cp = { p, (void*)__drake_lcmt_scope_data_get_hash };
    (void) cp;

    int64_t hash = 0xce3bf247025afc2fLL
         + __int64_t_hash_recursive(&cp)
         + __int32_t_hash_recursive(&cp)
         + __string_hash_recursive(&cp)
         + __boolean_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
         + __double_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __drake_lcmt_scope_data_get_hash(void)
{
    if (!__drake_lcmt_scope_data_hash_computed) {
        __drake_lcmt_scope_data_hash = __drake_lcmt_scope_data_hash_recursive(NULL);
        __drake_lcmt_scope_data_hash_computed = 1;
    }

    return __drake_lcmt_scope_data_hash;
}

int __drake_lcmt_scope_data_encode_array(void *buf, int offset, int maxlen, const drake_lcmt_scope_data *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].scope_id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &(p[element].num_points), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &(p[element].linespec), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &(p[element].resetOnXval), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].xdata), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &(p[element].ydata), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int drake_lcmt_scope_data_encode(void *buf, int offset, int maxlen, const drake_lcmt_scope_data *p)
{
    int pos = 0, thislen;
    int64_t hash = __drake_lcmt_scope_data_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __drake_lcmt_scope_data_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __drake_lcmt_scope_data_encoded_array_size(const drake_lcmt_scope_data *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int64_t_encoded_array_size(&(p[element].scope_id), 1);

        size += __int32_t_encoded_array_size(&(p[element].num_points), 1);

        size += __string_encoded_array_size(&(p[element].linespec), 1);

        size += __boolean_encoded_array_size(&(p[element].resetOnXval), 1);

        size += __double_encoded_array_size(&(p[element].xdata), 1);

        size += __double_encoded_array_size(&(p[element].ydata), 1);

    }
    return size;
}

int drake_lcmt_scope_data_encoded_size(const drake_lcmt_scope_data *p)
{
    return 8 + __drake_lcmt_scope_data_encoded_array_size(p, 1);
}

int __drake_lcmt_scope_data_decode_array(const void *buf, int offset, int maxlen, drake_lcmt_scope_data *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].scope_id), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &(p[element].num_points), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_decode_array(buf, offset + pos, maxlen - pos, &(p[element].linespec), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &(p[element].resetOnXval), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].xdata), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &(p[element].ydata), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __drake_lcmt_scope_data_decode_array_cleanup(drake_lcmt_scope_data *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_decode_array_cleanup(&(p[element].scope_id), 1);

        __int32_t_decode_array_cleanup(&(p[element].num_points), 1);

        __string_decode_array_cleanup(&(p[element].linespec), 1);

        __boolean_decode_array_cleanup(&(p[element].resetOnXval), 1);

        __double_decode_array_cleanup(&(p[element].xdata), 1);

        __double_decode_array_cleanup(&(p[element].ydata), 1);

    }
    return 0;
}

int drake_lcmt_scope_data_decode(const void *buf, int offset, int maxlen, drake_lcmt_scope_data *p)
{
    int pos = 0, thislen;
    int64_t hash = __drake_lcmt_scope_data_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __drake_lcmt_scope_data_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int drake_lcmt_scope_data_decode_cleanup(drake_lcmt_scope_data *p)
{
    return __drake_lcmt_scope_data_decode_array_cleanup(p, 1);
}

int __drake_lcmt_scope_data_clone_array(const drake_lcmt_scope_data *p, drake_lcmt_scope_data *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int64_t_clone_array(&(p[element].scope_id), &(q[element].scope_id), 1);

        __int32_t_clone_array(&(p[element].num_points), &(q[element].num_points), 1);

        __string_clone_array(&(p[element].linespec), &(q[element].linespec), 1);

        __boolean_clone_array(&(p[element].resetOnXval), &(q[element].resetOnXval), 1);

        __double_clone_array(&(p[element].xdata), &(q[element].xdata), 1);

        __double_clone_array(&(p[element].ydata), &(q[element].ydata), 1);

    }
    return 0;
}

drake_lcmt_scope_data *drake_lcmt_scope_data_copy(const drake_lcmt_scope_data *p)
{
    drake_lcmt_scope_data *q = (drake_lcmt_scope_data*) malloc(sizeof(drake_lcmt_scope_data));
    __drake_lcmt_scope_data_clone_array(p, q, 1);
    return q;
}

void drake_lcmt_scope_data_destroy(drake_lcmt_scope_data *p)
{
    __drake_lcmt_scope_data_decode_array_cleanup(p, 1);
    free(p);
}

int drake_lcmt_scope_data_publish(lcm_t *lc, const char *channel, const drake_lcmt_scope_data *p)
{
      int max_data_size = drake_lcmt_scope_data_encoded_size (p);
      uint8_t *buf = (uint8_t*) malloc (max_data_size);
      if (!buf) return -1;
      int data_size = drake_lcmt_scope_data_encode (buf, 0, max_data_size, p);
      if (data_size < 0) {
          free (buf);
          return data_size;
      }
      int status = lcm_publish (lc, channel, buf, data_size);
      free (buf);
      return status;
}

struct _drake_lcmt_scope_data_subscription_t {
    drake_lcmt_scope_data_handler_t user_handler;
    void *userdata;
    lcm_subscription_t *lc_h;
};
static
void drake_lcmt_scope_data_handler_stub (const lcm_recv_buf_t *rbuf,
                            const char *channel, void *userdata)
{
    int status;
    drake_lcmt_scope_data p;
    memset(&p, 0, sizeof(drake_lcmt_scope_data));
    status = drake_lcmt_scope_data_decode (rbuf->data, 0, rbuf->data_size, &p);
    if (status < 0) {
        fprintf (stderr, "error %d decoding drake_lcmt_scope_data!!!\n", status);
        return;
    }

    drake_lcmt_scope_data_subscription_t *h = (drake_lcmt_scope_data_subscription_t*) userdata;
    h->user_handler (rbuf, channel, &p, h->userdata);

    drake_lcmt_scope_data_decode_cleanup (&p);
}

drake_lcmt_scope_data_subscription_t* drake_lcmt_scope_data_subscribe (lcm_t *lcm,
                    const char *channel,
                    drake_lcmt_scope_data_handler_t f, void *userdata)
{
    drake_lcmt_scope_data_subscription_t *n = (drake_lcmt_scope_data_subscription_t*)
                       malloc(sizeof(drake_lcmt_scope_data_subscription_t));
    n->user_handler = f;
    n->userdata = userdata;
    n->lc_h = lcm_subscribe (lcm, channel,
                                 drake_lcmt_scope_data_handler_stub, n);
    if (n->lc_h == NULL) {
        fprintf (stderr,"couldn't reg drake_lcmt_scope_data LCM handler!\n");
        free (n);
        return NULL;
    }
    return n;
}

int drake_lcmt_scope_data_subscription_set_queue_capacity (drake_lcmt_scope_data_subscription_t* subs,
                              int num_messages)
{
    return lcm_subscription_set_queue_capacity (subs->lc_h, num_messages);
}

int drake_lcmt_scope_data_unsubscribe(lcm_t *lcm, drake_lcmt_scope_data_subscription_t* hid)
{
    int status = lcm_unsubscribe (lcm, hid->lc_h);
    if (0 != status) {
        fprintf(stderr,
           "couldn't unsubscribe drake_lcmt_scope_data_handler %p!\n", hid);
        return -1;
    }
    free (hid);
    return 0;
}

