#!/bin/sh

  ./sntoya
  ./sntoyb
  ./snmaina
  ./snmainb
  ./snmainc
  ./snmemtesta
  ./snmemtestb
  ./testera
  ./t1dieta
  ./t1dietb
  ./t2bananaa
  ./t2bananab
  ./t3qp
  ./t4mannea
  ./t4manneb
  ./t5weapon
  ./t6wood
  ./t7etamacro
  ./calvara
  ./catmixa
  ./catmixb
  ./catmixc
  ./springa
  ./springb
  ./springib
  ./maxi
  ./npmain
  ./hsmaina
  ./hsmainc
  ./slmain
  ./sqmain
  ./sqmain2
  ./hs118
  ./slmainMPS
  ./sqmainMPS
#  ./adlittle
#  ./pilot4
#  ./refinery
