/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package drake.examples.Pendulum;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class lcmt_pendulum_x implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public double theta;
    public double thetaDot;
 
    public lcmt_pendulum_x()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xe63ab1618c3683f1L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(drake.examples.Pendulum.lcmt_pendulum_x.class))
            return 0L;
 
        classes.add(drake.examples.Pendulum.lcmt_pendulum_x.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        outs.writeDouble(this.theta); 
 
        outs.writeDouble(this.thetaDot); 
 
    }
 
    public lcmt_pendulum_x(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public lcmt_pendulum_x(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static drake.examples.Pendulum.lcmt_pendulum_x _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        drake.examples.Pendulum.lcmt_pendulum_x o = new drake.examples.Pendulum.lcmt_pendulum_x();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.theta = ins.readDouble();
 
        this.thetaDot = ins.readDouble();
 
    }
 
    public drake.examples.Pendulum.lcmt_pendulum_x copy()
    {
        drake.examples.Pendulum.lcmt_pendulum_x outobj = new drake.examples.Pendulum.lcmt_pendulum_x();
        outobj.timestamp = this.timestamp;
 
        outobj.theta = this.theta;
 
        outobj.thetaDot = this.thetaDot;
 
        return outobj;
    }
 
}

